author: Kristijan Cetina
title: Kristijan Cetina | home page in experimental phase
description: >- # this means to ignore newlines until "baseurl:"
  Just a simple static web page for learning and experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kristijancetina.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true

header_pages:
  - about.md
  - index.html

twitter_username: kristijancetina
github_username:  kristijancetina

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed